CREATE TABLE USER_ (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);


CREATE TABLE ROOM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER_(id)
);

CREATE TABLE MODE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    frequency_days INT NOT NULL
);

CREATE TABLE TASK (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_done BOOLEAN DEFAULT FALSE,
    added_on DATETIME DEFAULT CURRENT_TIMESTAMP,
    done_on DATETIME NULL,
    room_id INT NOT NULL,
    mode_id INT,
    FOREIGN KEY (room_id) REFERENCES ROOM(id),
    FOREIGN KEY (mode_id) REFERENCES MODE(id)
);

CREATE TABLE TIMELINE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    start_date DATE NOT NULL,
    deadline DATE NOT NULL,
    FOREIGN KEY (task_id) REFERENCES TASK(id)
);
